### PR TITLE
126 issuerdenom

### LINKED ISSUE #126: Creating a new issuer should also populate denom metadata
**Describe the bug**
Adding a new issuer does not update the denom metadata (see #123).

**Expected behavior**
Adding a new issuer should populate the denom metadata (see #123).

To this end, some additional information must be passed in the CreateIssuer message:
- **base denom**, e.g. "eeur" (already present)
- **display denom**, e.g. "EEUR" (missing)
- **exponent**, e.g. 6 (missing)
- **description**, e.g. "e-Money EUR Stablecoin" (missing)

Based on the above example, the metadata would be populated as follows:
```
{
    "base": "eeur",
    "description": "e-Money EUR stablecoin",
    "display": "EEUR",
    "denom_units": [
      {
        "aliases": [],
        "denom": "eeur",
        "exponent": 6
      }
    ]
}
```

### PR DESCRIPTION
**Pull request by blewater**
Closes #126

Adding denom metadata when creating an issuer.

### CODE REVIEW

File: x/issuer/keeper/keeper.go [hunk 1]
```diff
@@ -189,7 +198,26 @@ func (k Keeper) AddIssuer(ctx sdk.Context, newIssuer types.Issuer) (*sdk.Result,
...
+				Description: "e-Money EUR stablecoin",
+				DenomUnits: []*banktypes.DenomUnit{
+					{
+						Denom:    denom,
+						Exponent: 6,
+						Aliases:  nil,
+					},
+				},
+				Base:    denom,
+				Display: strings.ToUpper(denom),
```
Comment (haasted) [inline x/issuer/keeper/keeper.go:213]: Would also be nice to have this parameterizable. Optional flags would be nice here, e.g. `emd tx ... --display "eEUR" --description "THE Euro stablecoin"`. If omitted, the description should be empty, while the `display` value should be the uppercased denom (as it is now).

**Review by haasted — CHANGES_REQUESTED** [review]

**Review by haasted — APPROVED** [review]
